#!/usr/bin/Rscript

## Pie and bar Charts of Ensembl genes

######################## Ensembl Annotation classification ###############
# Description:
# Rscript CBS-miRSeq.ensembl.gene_v1.R <hsa.ensembl.report.txt> <output.dir>
# Parameters:
# ncRNA.expr  = expression generated by module 2
# output.dir= Path where results should be produced
# date: 14 April 2015
# version : v1.0
# Authors: Keshrwani RK email: bioinforupesh2009.au@gmail.com
# Copyright (c) 2019 Kesharwani RK
##########################################################################

#############################################
#exp:
#ncRNA.expr <- "sps.ensembl.report.txt"
#output.dir <- "/.../hsa_ensembl_class"
#############################################
#input
arg <- commandArgs(TRUE)
if(length(arg) < 2)
{
 stop("Not enough arguments. Please supply all arguments. \nUSAGE: Rscript ./CBS-miRSeq.ensembl.gene_v1.R <sps.ensembl.report.txt> <output.dir>")
}
ncRNA.expr <- arg[1]
output.dir <- arg[2]

cat("Finding Ensembl biotypes in each sample..\n")
cat("Analysis started....\n")
cat ("date & time:\n")
date()

# Check, install packages and load packages
if("plotrix" %in% rownames(installed.packages()) == FALSE) install.packages("plotrix",dep=TRUE,repos='http://star-www.st-andrews.ac.uk/cran/')
# Load packages into session 
suppressMessages(require("plotrix"))
##cat("\n#Distribution of Ensembl biotypes..\n", arg[1], "to", arg[2], "\n")
#loading data
data=read.table(ncRNA.expr,header=T,row.names=1)
#head(data)
## create matrix 
data_mat=as.matrix(data[,1:ncol(data)])
colr =rainbow(nrow(data_mat))
#plot
pdf(paste(output.dir,"/","Ensembl_biotypes_pie_bar.pdf",sep=""),width=15,height=10)
#par(mfrow = c(ncol(data)/2, 2)) ## 2 rows 2 columns
par(mfrow = c(2, 2))
for (i in 1:ncol(data_mat)) {
 pie3D(data_mat[,i],labels="", explode=0.2, radius=1,height=0.1,col = colr,theta=pi/4,start=5, main = paste("Ensembl biotypes for sample", colnames(data[i]), split = ""))
 ##legend
 par(xpd=TRUE)
 legend(1,0.60,cex = 0.90, fill = colr, legend = paste(c(row.names(data_mat)),round(data_mat[,i]/sum(data_mat[,i])*100,1),"%",sep=" "),bty = "n")
}
#graphics.off()

#pdf(paste(output.dir,"/","Ensembl gene classification_bar.pdf",sep=""),width=15,height=10)
#par(mfrow = c(ncol(data)/2, 2)) ## 2 rows 2 columns
# barplots and sample %
for (i in 1:ncol(data_mat)) {
 barplot(data_mat[,i],names.arg="",las=2, width = 1, ylim = range(pretty(c(0, data_mat[,i]))), col = topo.colors(nrow(data_mat)),main = paste("Ensembl biotypes for sample", colnames(data[i]), split = ""))
 ##legend
 legend("topright", inset = 0.03, fill = topo.colors(nrow(data_mat)), legend = paste(c(row.names(data_mat)),round(data_mat[,i]/sum(data_mat[,i])*100,1),"%",sep=" "),bty = "n")
 }
cat ("done.\n")
dev.off()
cat("\n#Pie and Bar plots of Ensembl biotype has been created., 
Go to your output.dir to check results.....\n\n")
